In [1]:
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LAParams, LTTextBox, LTTextLine, LTFigure
import pandas as pd
import numpy as np
import re

def parse_layout(layout, a, b):
    
    textDf = pd.DataFrame(columns=['x1', 'y1', 'x2', 'y2','y','text'])
    
    """Function to recursively parse the layout tree."""
    for lt_obj in layout:
        if isinstance(lt_obj, LTTextBox) or isinstance(lt_obj, LTTextLine):
            for obj in lt_obj:
                s = pd.Series({'x1':int(obj.bbox[0]), 'y1':int(obj.bbox[1]),'x2':int(obj.bbox[2]), 
                               'y2':int(obj.bbox[3]), 'y':float(0), 'text':obj.get_text().replace("\n", '')})
                textDf = textDf.append(s, ignore_index = True)  

    textDf = textDf.sort_values(['x1','y1'], ascending=True).reset_index(drop = True)
    
    row_startDf = textDf[textDf['x1'] < textDf['x1'].min(axis=0) + b]
    
#     for i in range(len(textDf)):
#         print (textDf.iloc[i]['text'])
#         if 'End of course result history' in textDf.iloc[i]['text']:
#             print(i)
#             s = pd.Series({'x1':textDf.iloc[i]['x1'], 'y1':int(textDf.iloc[i]['y1']),'x2':int(textDf.iloc[i]['x2']), 
#                                'y2':int(textDf.iloc[i]['y2']), 'y':float(0), 'text':textDf.iloc[i]['text']})
#             row_startDf.append(s, ignore_index = True)
    
    rows = row_identifier(row_startDf, a)
    
    for i in range(len(textDf)):
        y = -1
        for j in range(len(rows)):
            if float(textDf.iloc[i]['y2']) < rows.iloc[j]['upper_y'] and float(textDf.iloc[i]['y1']) > rows.iloc[j]['lower_y']:
                y = rows.iloc[j]['y']
                break
        #textDf.set_value(i, 'y', y)
        textDf.at[i:i, 'y'] = y
    
    return textDf

def row_identifier(row_startDf, a):
    rows = pd.DataFrame(columns=['lower_y', 'upper_y', 'y'])
    height = row_startDf['y2']-row_startDf['y1']
    rows['upper_y'] = row_startDf['y2'] + height*a
    rows['lower_y'] = row_startDf['y1'] - height*a
    rows['y'] = (rows['upper_y'] + rows['lower_y'])/2
    return rows 
       

def convert_to_df(text):
    
        student = []
        course = []
        mark = []
        result = []
        indexMark = -1
        indexResultS = -1
        indexResultE = -1
        
        table_start = 0
        table_end = 0
        
        for i in range(len(text)):
            content = text.iloc[i]['text']
            temp = content.split(',')
            if 'Student name' in temp[0]:
                student.append(temp[0][12:].lstrip())
            elif 'Student ID' in temp[0]:
                student.append(temp[0][10:].lstrip())
            elif 'Student course ID' in temp[0]:
                student.append(temp[0][17:].lstrip())
            elif temp[0] == 'Course':
                course.append(temp[1])
            elif len(temp) == 1 and 'Credit points obtained' in temp[0]:
                course.append(temp[0][22:])
            elif len(temp) == 2 and 'Credit points obtained' in temp[0]:
                course.append(temp[1])
            elif len(temp) == 2 and 'Major' in temp[0]:
                course.append(temp[1])
            elif 'Unit of Study Results' in temp[0]:
                table_start = i + 2
            elif 'Credit points gained' in temp[0]:
                table_end = i - 1
            elif len(temp) == 4 and temp[0] == 'Year':
                indexMark = i
                break
                       
        if table_end != 0:
            for i in range(table_start, table_end + 1):
                        content = text.iloc[i]['text']
                        temp = content.split(',')
                        
                        if 'Year' in temp[0]:
                            continue
                        temp0 = temp[0].split(' ')

                            
                        if (len(temp0) == 3):
                            temp.pop(0)
                            temp.insert(0, temp0[2])
                            temp.insert(0, temp0[1])
                            temp.insert(0, temp0[0])
                        elif len(temp0) == 2:
                            temp.pop(0)
                            temp.insert(0, temp0[1])
                            temp.insert(0, temp0[0])
                            
                        if len(temp) == 6:
                            temp1 = temp[4].split(' ')
                            if(len(temp1) == 1):
                                temp.insert(4, '')
                            elif len(temp1) == 2:
                                temp.pop(4)
                                temp.insert(4, temp1[1])
                                temp.insert(4, temp1[0])
                            
                        result.append(temp)
        else:
            for i in range(table_start, len(text)):
                        content = text.iloc[i]['text']
                        temp = content.split(',')
                        if 'Year' in temp[0]:
                            continue
                        temp0 = temp[0].split(' ')
                            
                        if (len(temp0) == 3):
                            temp.pop(0)
                            temp.insert(0, temp0[2])
                            temp.insert(0, temp0[1])
                            temp.insert(0, temp0[0])
                        elif len(temp0) == 2:
                            temp.pop(0)
                            temp.insert(0, temp0[1])
                            temp.insert(0, temp0[0])
                            
                        if len(temp) == 6:
                            temp1 = temp[4].split(' ')
                            if(len(temp1) == 1):
                                temp.insert(4, '')
                            elif len(temp1) == 2:
                                temp.pop(4)
                                temp.insert(4, temp1[1])
                                temp.insert(4, temp1[0])
                            
                        result.append(temp)

        if text.iloc[len(text)-1]['text'] == 'End of course result history':        
            #print("end")
            for i in range(indexMark, len(text)-1):
                content = text.iloc[i]['text']
                temp = content.split(',')
                if 'Year' in temp[0]:
                            continue
                mark.append(temp)
            mark = [y for x in mark for y in x]
            mark = np.reshape(mark, (-1, 4))
        elif indexMark > -1:
            #print("no end")
            for i in range(indexMark+1, len(text)):
                content = text.iloc[i]['text']
                temp = content.split(',')
                mark.append(temp)
    
        #s = pd.Series({'Student name':student[0], 'Student ID':student[1], 'Student course ID':student[2]})
        studentDf = pd.DataFrame(columns = ('Student name', 'Student ID', 'Student course ID'), data = [student])
        if len(course) == 3:
            courseDf = pd.DataFrame(columns = ('Course', 'Credit points obtained', 'Major(s)'), data = [course])
        elif len(course) == 2:
            courseDf = pd.DataFrame(columns = ('Course', 'Credit points obtained'), data = [course])
        marksDf = pd.DataFrame(columns = ('Year', 'Session', 'Semester average mark', 'Annual average mark'), data = mark)
        resultDf = pd.DataFrame(columns = ('Year', 'Session', 'Unit of study code', 'Unit of study name', 'Mark', 'Grade', 'Credit points'), data = result)
    
        return studentDf, courseDf, marksDf, resultDf

In [2]:
def convert_to_df2(text):
    result = []
    mark = []
    markSum = []
    indexResult = 0
    indexMark = 0
    for i in range(len(text)-1):
        content = text.iloc[i]['text']
        temp = content.split(',')
        if 'Credit points gained' in content:
            indexResult = i+1
            break
        elif temp[0] == 'Year':
#             print("2")
            indexMark = i+1
            break
    
    if indexResult > 0:
        if indexResult != 1:
            for i in range(0,indexResult-1): 
                content = text.iloc[i]['text']
                temp = content.split(',')
                if 'Year' in temp[0]:
                    continue
                temp0 = temp[0].split(' ')
                    
                if (len(temp0) == 3):
                    temp.pop(0)
                    temp.insert(0, temp0[2])
                    temp.insert(0, temp0[1])
                    temp.insert(0, temp0[0])
                elif len(temp0) == 2:
                    temp.pop(0)
                    temp.insert(0, temp0[1])
                    temp.insert(0, temp0[0])
                    
                if len(temp) == 6:
                    temp1 = temp[4].split(' ')
                    if(len(temp1) == 1):
                        temp.insert(4, '')
                    elif len(temp1) == 2:
                        temp.pop(4)
                        temp.insert(4, temp1[1])
                        temp.insert(4, temp1[0])
                    
                result.append(temp)

        for i in range(indexResult+2, len(text)-1):
            content = text.iloc[i]['text']
            temp = content.split(',')
            mark.append(temp)

    if indexMark > 0 :
        
        for i in range(indexMark, len(text)-1):
            content = text.iloc[i]['text']
            temp = content.split(',')
            mark.append(temp)
        
    elif indexMark == 0 and indexResult == 0:
        for i in range(len(text)-1):
            content = text.iloc[i]['text']
            temp = content.split(',')  #['','','','']
            mark.append(temp)           
                
    resultDf = pd.DataFrame(columns = ('Year', 'Session', 'Unit of study code', 'Unit of study name', 'Mark', 'Grade', 'Credit points'), data = result)
    marksDf2 = pd.DataFrame(columns = ('Year', 'Session', 'Semester average mark', 'Annual average mark'), data = mark)
        
    return resultDf, marksDf2

In [3]:

def convert_pdf_to_df(file):
    
    fp = open(file, 'rb')
    parser = PDFParser(fp)
    doc = PDFDocument(parser)
    
    rsrcmgr = PDFResourceManager()
    laparams = LAParams()
    device = PDFPageAggregator(rsrcmgr, laparams=laparams)
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    
    textDf = pd.DataFrame(columns=['x1', 'y1', 'x2', 'y2', 'text'])
    resultDf = pd.DataFrame(columns = ('Year', 'Session', 'Unit of study code', 'Unit of study name', 'Mark', 'Grade', 'Credit points'))
    marksDf2 = pd.DataFrame(columns = ('Year', 'Session', 'Semester average mark', 'Annual average mark'))
    resultDf2 = pd.DataFrame(columns = ('Year', 'Session', 'Unit of study code', 'Unit of study name', 'Mark', 'Grade', 'Credit points'))
    
    page_no = 1
    
    for page in PDFPage.create_pages(doc):
        
        interpreter.process_page(page)
        layout = device.get_result()
        textDf = parse_layout(layout, 0.3, 30)
        textDf['text'] = textDf['text'].apply(lambda x:','+ x)
        textDf1 = textDf.groupby(by='y')['text'].sum().reset_index()
        textDf1 = textDf1.sort_values('y', ascending=False)
        textDf1['text'] = textDf1['text'].apply(lambda x:x[1:])
        print(textDf1)
    
        if page_no == 1:
            studentDf, courseDf, marksDf, resultDf1 = convert_to_df(textDf1)
        elif page_no == 2:
            resultDf2, marksDf2 = convert_to_df2(textDf1)
            
        page_no += 1
        
    
    if marksDf2.empty == False:
        marksDf = pd.concat([marksDf, marksDf2])
    resultDf = pd.concat([resultDf1, resultDf2])
    
    return studentDf, courseDf, marksDf, resultDf

In [4]:
studentDf, courseDf, marksDf, resultDf = convert_pdf_to_df("transcript_bachelor.pdf")

        y                                               text
33  717.0                              Course result history
32  677.5  The details listed below are for the course Ba...
31  664.5  copy of your online result history and not an ...
30  646.0    Student name Zici Chen ,Printed on: 05/Sep/2019
29  633.5                             Student ID 480366271
28  621.5                      Student course ID 470376771/1
27  597.5                                     Course details
26  569.5             Course,Bachelor of Engineering Honours
25  554.5                          Credit points obtained 62
24  527.5                              Unit of Study Results
23  501.5  Year Session Unit of study code,Unit of study ...
22  484.5  2018 S1C,ENGG1111,Integrated Engineering 1,77....
21  469.5  2018 S1C,ENGG1800,Introduction to Engineering ...
20  453.5  2018 S1C,ENGG1801,Engineering Computing,70.0,CR,6
19  438.5  2018 S1C,ENGP1000,Professional Engagement Prog...
18  423.5         2018 S1C,MATH1002,Linear Algebra,84.0,DI,3
17  407.5  2018 S1C,MATH1021,Calculus Of One Variable,81....
16  392.5  2018 S2C,ELEC1601,Introduction to Computer Sys...
15  377.5  2018 S2C,ENGG2111,Integrated Engineering 2,82....
14  361.5  2018 S2C,INFO1110,Introduction to Programming,...
13  346.5  2018 S2C,INFO1113,Object-Oriented Programming,...
12  331.0  2018 S2C,MATH1005,Statistical Thinking with Da...
11  315.5  2018 S2C,MATH1023,Multivariable Calculus and M...
10  300.5    2019 S1C,COMP2017,Systems Programming,45.0,FA,0
9   285.5  2019 S1C,COMP2123,Data Structures and Algorith...
8   269.5          2019 S1C,ELEC2602,Digital Logic,80.0,HD,6
7   255.5  2019 S1C,ISYS2110,Analysis and Design of Web I...
6   239.0                            Credit points gained,68
5   212.5                                 Your Average Marks
4   185.5  Year,Session,Semester average mark ,Annual ave...
3   169.5                            2018,Semester 1,76.9,NA
2   153.5                          2018,Semester 2,81.5,74.1
1   139.5                            2019,Semester 1,65.8,NA
0    -1.0                       End of course result history

In [5]:
studentDf

  Student name   Student ID Student course ID
0   Zici Chen   480366271         470376771/1

In [6]:
courseDf

                            Course Credit points obtained
0  Bachelor of Engineering Honours                     62

In [7]:
resultDf

,Year,Session,Unit of study code,Unit of study name,Mark,Grade,Credit points
0,2018,S1C,ENGG1111,Integrated Engineering 1,77.0,DI,6
1,2018,S1C,ENGG1800,Introduction to Engineering Disciplines,78.0,DI,6
2,2018,S1C,ENGG1801,Engineering Computing,70.0,CR,6
3,2018,S1C,ENGP1000,Professional Engagement Program 1,,UC,0
4,2018,S1C,MATH1002,Linear Algebra,84.0,DI,3
5,2018,S1C,MATH1021,Calculus Of One Variable,81.0,DI,3
6,2018,S2C,ELEC1601,Introduction to Computer Systems,83.0,DI,6
7,2018,S2C,ENGG2111,Integrated Engineering 2,82.0,DI,2
8,2018,S2C,INFO1110,Introduction to Programming,73.0,CR,6
9,2018,S2C,INFO1113,Object-Oriented Programming,55.0,PS,6
10,2018,S2C,MATH1005,Statistical Thinking with Data,74.0,CR,3
11,2018,S2C,MATH1023,Multivariable Calculus and Modelling,69.0,CR,3
12,2019,S1C,COMP2017,Systems Programming,45.0,FA,0
13,2019,S1C,COMP2123,Data Structures and Algorithms,59.0,PS,6
14,2019,S1C,ELEC2602,Digital Logic,80.0,HD,6
15,2019,S1C,ISYS2110,Analysis and Design of Web Info Systems,90.0,HD,6

In [8]:
marksDf

   Year     Session Semester average mark Annual average mark
0  2018  Semester 1                  76.9                  NA
1  2018  Semester 2                  81.5                74.1
2  2019  Semester 1                  65.8                  NA

In [ ]:
    def getValueByKey(self, pages, interpreter, device, keyWord):
        for page in pages:
            interpreter.process_page(page)
            layout = device.get_result()
            for x in layout:
                    if isinstance(x, LTTextBox) or isinstance(x, LTTextLine):
                    
                        rowIndex = 0
                        columnIndex = 0
                        for y in x:
                            if(y.get_text() == keyWord + '\n'):
                                rowIndex = y.bbox[0]
                                columnIndex = y.bbox[1]
                                break
                        
                        if(rowIndex != 0 and columnIndex != 0):
                            for x1 in layout:
                                if isinstance(x1, LTTextBox) or isinstance(x1, LTTextLine):
                                    for y1 in x1:
                                        if(y1.bbox[1] == columnIndex and y1.bbox[0] != rowIndex):
                                            return y1.get_text().strip()

    def getValueBySplit(self, pages, interpreter, device, keyWord):
        for page in pages:
            interpreter.process_page(page)
            layout = device.get_result()
            for x in layout:
                 if isinstance(x, LTTextBox) or isinstance(x, LTTextLine):
                        for y in x:
                            if (keyWord in y.get_text()):
                                return y.get_text().strip('\n').split(keyWord)[1]
                            
    def getAverageByLocation(self, pages, interpreter,device, keyWord):
#         print(dir(pages))
        format_years = []
        format_semesters = []
        format_sams = []
        format_aams = []
        n = 0
        for page in pages:
            interpreter.process_page(page)
            layout = device.get_result()
            count = 0
            if n == 1:
                for x in layout:
                    if isinstance(x, LTTextBox) or isinstance(x, LTTextLine):
#                         print(x.get_text())
                        if count == 0:
                            years = x.get_text().split('\n')

                            for year in years:
                                if(year != 'Year' and year != ''):
                                    format_years.append(year)
#                             print(format_years)
                            count += 1
                        elif count == 1:
                            semesters = x.get_text().split('\n')
                            for semester in semesters:
                                if(semester != 'Session' and semester != ''):
                                    format_semesters.append(semester)
                            count += 1
                        elif count == 2:
                            sams = x.get_text().split('\n')
                            for sam in sams:
                                if(sam != ''):
                                    format_sams.append(sam.replace('\n', ''))
                            count += 1
                        elif count == 3:
                            aams = x.get_text().split('\n')
                            for aam in aams:
                                if(aam != ''):
                                    format_aams.append(aam.replace('\n', ''))
                            count += 1
                a = pd.DataFrame({'Year': format_years, 'Session': format_semesters, 'Semester average mark': format_sams, 'Annual average mark': format_aams})
                return a
            n += 1
        
            for x in layout:
                if isinstance(x, LTTextBox) or isinstance(x, LTTextLine):

                    rowIndex = 0
                    columnIndex = 0
                    for y in x:
                        if(y.get_text() == keyWord + '\n'):
                            rowIndex = y.bbox[0]
                            columnIndex = y.bbox[1]
                            break

                    if(rowIndex != 0 and columnIndex != 0):
                        format_years = []
                        format_semesters = []
                        format_sams = []
                        format_aams = []
                        index = 0

                        for x1 in layout:
                            if isinstance(x1, LTTextBox) or isinstance(x1, LTTextLine):
                                if(x1.bbox[1] < columnIndex):
#                                     print(x1.get_text())
                                    if(index == 0):
                                        years = x1.get_text().split('\n')
                                        for year in years:
                                            if(year != 'Year' and year != ''):
                                                format_years.append(year)
                        #page1
#                                     if(index == 1):
#                                         semesters = x1.get_text().split('\n')
#                                         for semester in semesters:
#                                             if(semester != 'Session' and semester != ''):
#                                                 format_semesters.append(semester)
                                                    
#                                     if(index == 4):
#                                         sams = x1.get_text().split('\n')
#                                         for sam in sams:
#                                             if(sam != ''):
#                                                 format_sams.append(sam.replace('\n', ''))
                                                
#                                     if(index == 5):
#                                         aams = x1.get_text().split('\n')
#                                         for aam in aams:
#                                             if(aam != ''):
#                                                 format_aams.append(aam.replace('\n', ''))
                         #page2
                                    if(index == 2):
                                        semesters = x1.get_text().split('\n')
                                        for semester in semesters:
                                            if(semester != 'Session' and semester != ''):
                                                format_semesters.append(semester)

                                    if(index == 5):
                                        sams = x1.get_text().split('\n')
                                        for sam in sams:
                                            if(sam != ''):
                                                format_sams.append(sam.replace('\n', ''))

                                    if(index == 6):
                                        aams = x1.get_text().split('\n')
                                        for aam in aams:
                                            if(aam != ''):
                                                format_aams.append(aam.replace('\n', ''))

                                    index = index + 1

        a = pd.DataFrame({'Year': format_years, 'Session': format_semesters, 'Semester average mark': format_sams, 'Annual average mark': format_aams})
        return a

In [ ]:
import pandas as pd
from tabula import wrapper

path = 'DemoTranscript.pdf'

file = open(path, 'rb')
praser = PDFParser(file)
doc = PDFDocument(praser, password='')
if not doc.is_extractable:
    raise PDFTextExtractionNotAllowe
rsrcmgr = PDFResourceManager(caching = False)
laparams = LAParams()
device = PDFPageAggregator(rsrcmgr, laparams=laparams)
interpreter = PDFPageInterpreter(rsrcmgr, device)

In [ ]:
Student_name = []
Student_name.append(pdf2TxtManager.getValueBySplit(PDFPage.create_pages(doc), interpreter, device, 'Student name '))
Student_id = []
Student_id.append(pdf2TxtManager.getValueBySplit(PDFPage.create_pages(doc), interpreter, device, 'Student ID '))
Student_course_id = []
Student_course_id.append(pdf2TxtManager.getValueBySplit(PDFPage.create_pages(doc), interpreter, device, 'Student course ID '))
student = [Student_name + Student_id + Student_course_id]

student_info = pd.DataFrame(columns = ('Studnet name', 'Student ID', 'Student course ID'), data = student)
# student_info = pd.DataFrame({'Studnet name': Student_name, 'Student ID': Student_id, 'Student course ID': Student_course_id})
        
print("-------This student information-------")
student_info
# student_info.sort_index(axis=1, ascending=False)

In [ ]:
value_course = []
value_course.append(pdf2TxtManager.getValueByKey(PDFPage.create_pages(doc), interpreter, device, 'Course'))
value_major = []
value_major.append(pdf2TxtManager.getValueByKey(PDFPage.create_pages(doc), interpreter, device, 'Major(s)'))
Credit_points_obtained = []
Credit_points_obtained.append(pdf2TxtManager.getValueBySplit(PDFPage.create_pages(doc), interpreter, device, 'Credit points obtained '))
courseDetails = [value_course + value_major + Credit_points_obtained]

course_details = pd.DataFrame(columns = ('Course', 'Major(s)', 'Credit points obtained'), data = courseDetails)
# course_details = pd.DataFrame(columns = {'Course', 'Major(s)', 'Credit points obtained'}, data = courseDetails)
# course_details = pd.DataFrame({'Course': value_course, 'Credit points obtained': Credit_points_obtained, 'Major(s)': value_major})

print("\n-------This course details-------")
course_details

In [ ]:
df = wrapper.read_pdf('DemoTranscript.pdf')
df

In [ ]:



# list = pdf2TxtManager.getAverageByLocation(PDFPage.create_pages(doc), interpreter, device, 'Your Average Marks')
# print("\n-------This average marks-------")
# list.sort_index(axis=1, ascending=False)
list = pdf2TxtManager.getAverageByLocation(PDFPage.create_pages(doc), interpreter, device, 'Your Average Marks')
print("\n-------This average marks-------")
list.sort_index(axis=1, ascending=False)

In [ ]:
path = 'Demotranscript.pdf'

file = open(path, 'rb')
praser = PDFParser(file)
doc = PDFDocument(praser, password='')
if not doc.is_extractable:
    raise PDFTextExtractionNotAllowe
rsrcmgr = PDFResourceManager(caching = False)
laparams = LAParams()
device = PDFPageAggregator(rsrcmgr, laparams=laparams)
interpreter = PDFPageInterpreter(rsrcmgr, device)
pages = PDFPage.create_pages(doc)

text  = []
y_axis = []
x_axis = []

data = pd.DataFrame(columns = ('y-axis', 'x-axis', 'text'))
for page in pages:
    interpreter.process_page(page)
    layout = device.get_result()
    for x in layout:
            if isinstance(x, LTTextBox) or isinstance(x, LTTextLine):
                for y in x:
                    text.append(y.get_text())
                    y_axis.append(int(y.bbox[1]))
                    x_axis.append(round(y.bbox[0], 2))

data['y-axis'] = y_axis
data['text'] = text
data['x-axis'] = x_axis

# data = data.sort_values(by = 'y-axis')

student_detail = pd.DataFrame(columns = ('Student name', 'Student ID', 'Student course ID'))
course_detail = pd.DataFrame(columns = ('Course', 'Credit points obtained', 'Major(s)'))
average_mark = pd.DataFrame(columns = ('Year', 'Session', 'Semester average mark', 'Annual average mark'))

course_row = 0
course_column = 0
major_row = 0
major = column = 0

for index, row in data.iterrows():
    if 'Student name' in row['text']:
        student_detail['Student name'] = [row['text'].strip('\n').split('Student name ')[1]]
    if 'Student ID' in row['text']:
        student_detail['Student ID'] = [row['text'].strip('\n').split('Student ID ')[1]]
    if 'Student course ID' in row['text']:
        student_detail['Student course ID'] = [row['text'].strip('\n').split('Student course ID ')[1]]
    if 'Credit points obtained' in row['text']:
        course_detail['Credit points obtained'] = [row['text'].strip('\n').split('Credit points obtained ')[1]]

        

def getCourseDetail(data, keyWord, course_detail):
    rowIndex = 0
    columnIndex = 0
    keyWord_1 = keyWord + '\n'
    
    for index, row in data.iterrows():
        if keyWord_1 in row['text']:
            columnIndex = row['y-axis']
            rowIndex = row['x-axis']

    for index, row in data.iterrows():
        if row['y-axis'] == columnIndex and row['x-axis'] != rowIndex:
            course_detail[keyWord] = [row['text'].strip('\n')]
            
getCourseDetail(data, 'Course', course_detail)
getCourseDetail(data, 'Major(s)', course_detail)

def getAverageMark(data, keyWord, average_mark):
    index = 0
    columnIndex = 0
    for index, row in data.iterrows():
        if keyWord in row['text']:
            columnIndex = row['y-axis']
    
    for index, row in data.iterrows():
        if row['y-axis'] < columnIndex and 'Year' in row['text']:
            index += 1
            break
        elif row['y-axis'] < columnIndex and index < 2:
            average_mark['Year'] = [row['text'].strip('\n')]
        elif row['y-axis'] < columnIndex and 'Session' in row['text']:
            index += 1
            break
        elif row['y-axis'] < columnIndex and index < 3:
            average_mark['Session'] = [row['text'].strip('\n')] 
        elif row['y-axis'] < columnIndex and 'Semester average mark' in row['text']:
            index += 1
            break        
        elif row['y-axis'] < columnIndex and index < 4:
            average_mark['Session'] = [row['text'].strip('\n')]         
            
            

getAverageMark(data, 'Your Average Marks', average_mark)       
        


data

In [ ]:
student_detail

In [ ]:
course_detail